[colors.bright]
black = "0x414166"
blue = "0x66ccff"  # Brighter soft blue
cyan = "0x66ffff"  # Brighter soft cyan
green = "0x66ffad"  # Brighter soft green
magenta = "0xff66ff"  # Brighter soft magenta
red = "0xff6699"  # Brighter soft pink
white = "0xffffff"
yellow = "0xffcc66"  # Brighter soft yellow

[colors.normal]
black = "0x2c2c3d"
blue = "0x3399ff"  # Soft blue
cyan = "0x33cccc"  # Soft cyan
green = "0x33cc85"  # Soft green
magenta = "0xcc33cc"  # Soft magenta
red = "0xff3366"  # Soft pink
white = "0xd8dee9"  # Kept the same as your original config
yellow = "0xffaa00"  # Soft yellow

[colors.primary]
background = "0x0c0c16"  # Kept the same as your original config
foreground = "0xd8dee9"  # Kept the same as your original config

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[window.padding]
x = 25
y = 25
